Update Vulnerability-Scan.md
Azure-Samples/kubernetes-offer-samples pull request #20
Opened 2023-06-23 02:17 UTC by maanasagovi

removed images with sensitive information

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2023-06-26 21:17 UTC, thomasyip-msft commented on getting-started/Vulnerability-Scan.md
> -<p align="center"><img src="images/step6-vulnerabilities.png" alt="step6-vulnerabilities" width="800"/>
remove the actual image too?

2023-07-02 23:05 UTC, janeguo-msft commented on getting-started/Vulnerability-Scan.md
> -<p align="center"><img src="images/step6-vulnerabilities.png" alt="step6-vulnerabilities" width="800"/>
Yeah, I think you should.

2023-07-02 23:06 UTC, janeguo-msft commented on getting-started/Vulnerability-Scan.md
> -<p align="center"><img src="images/step6-vulnerabilities.png" alt="step6-vulnerabilities" width="800"/>
> remove the actual image too?

Yeah, I think you should.

2023-07-02 23:09 UTC, janeguo-msft requested changes
Please remove the image files in the folder as well.

2023-07-17 20:35 UTC, janeguo-msft approved these changes

2023-07-17 21:44 UTC, janeguo-msft commented
#sign-off

2023-07-18 19:26 UTC, merged